### ISSUE TITLE
Spring Boot QuickStarter fails to deploy when provisioned

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-project-quickstarters#446] opened 2019-11-27 09:34 UTC
When someone deploys a new clean SpringBoot QS Jenkins reports:
```
Recording test results
No test report files were found. Configuration error?

```
The QS should work out of the box and If someone hasn't written any tests yet the following line should be comment out:
```
junit 'build/test-results/test/*.xml'
```
But I would say that is not the desirable solution.

**Comment by michaelsauter** [comment] 2019-11-27 10:25
Duplicate of https://github.com/opendevstack/ods-quickstarters/issues/50.

I'm closing the issue here since 1.2.x worked, but master of `ods-project-quickstarters` does not but will not be fixed as it won't be part of the 2.0 release.

**Closed by michaelsauter** 2019-11-27 10:25 UTC
Labels: bug
